### ISSUE TITLE
Lose notifications after reboot

### ISSUE THREAD

**Issue by jagosta** [ogra1/mattermost-client#1]
When I first install the snap it works great. However, after I reboot my system I lose notifications on the mattermost-client icon. 

I am running Ubuntu 20.04, and I save the client as a favorite. The client app will show that I have a new message, but I do not get the notification indicator on the icon.  If I uninstall and reinstall the client snap, then it will work again and show the notification indicator -- until the next reboot.

**Comment by ogra1** [comment]
note that the server provides no clean API for counting unread direct messages and i havent found a proper workaround for this yet that wouldnt end up eating a lot CPU (like constantly polling the whole list of channels and their state). are the counts for messages you are missing in a normal public/private channel or are they for direct messages ?

**Comment by jagosta** [comment]
I may need to recheck this by uninstalling and reinstalling, but I do not recall seeing a "count".  I thought it was just a symbol. 
If I am at computer when a new message comes in, I do get the gnome message.  

In the iphone app: I also get an immediate notification with a new message indicator.

**Comment by ogra1** [comment]
there are two indicators:
this one shows that "any conversation happened while the app was hidden"

![](https://dashboard.snapcraft.io/site_media/appmedia/2020/06/shot2.png)

and this one shows the count of unread mentions of your name or "@all", "@here", "@channel" while the app was hidden

![](https://dashboard.snapcraft.io/site_media/appmedia/2020/06/shot1.png)

both of these are updated every 20sec and show content only if the app is hidden/closed

**Comment by jagosta** [comment]
The top toolbar indicator is working.  IMHO, this one less interesting because it will change color for any conversation. 

The application icon is the one in question. And, it probably did have a number on it as shown. What is interesting in your last comment is that you only update this indicator and count if the window is hidden.  In my case, the window is never hidden as I always have it open on a small secondary monitor. So, I have to constantly check it for new messages, or right now I rely upon my phone to tell me. 

So, I can try and iconize the window to see it changes behavior.  What is interesting though is that it would show the indicator on first install prior to a reboot. 

Any reason why you only update indicator if the window is hidden?  This does not match my use model.  :-(

**Comment by jagosta** [comment]
I tested with the client iconized and it still failed to update the indicator.  :-(

**Comment by ogra1** [comment]
what do you mean by "iconized" ? 

the app is designed so that you should/can actually completely close it with the X button ... it will then completely free all CPU resources but keep the counting intact ... you can not actually close the app with its close button, it will always minimize to tray (to actually stop it you need to use the quit option from the menu of the tray icon) ... 

if we can prove this part works for you as desired and there is no other bug, i can look at loosening the conditions a little and make the counter count also when the window is unfocused and not just when it is closed ...

**Comment by jagosta** [comment]
hmm, it is not clear to me what you are stating.  When should and when should not it update?  Right now i cannot get it to update without uninstalling and reinstalling

**Comment by ogra1** [comment]
please start the app, close it with the X button of the window or from the trayicon menu (minimize to tray) and wait until you get a ping, see if the number indicator shows up/increases within 20sec ...

feel free to ask me to ping you ... 

i think the app works as desired (only showing indicator counts while it is minimized to tray) but we need to verify this first. 

i see that our expectations are different (the design i developed is to have the app 90% of the time closed and not eat any system resources but to still notify you) and i'll happily adjust it to also show counts while it is on screen but not focused but i want to make sure that we do not hit an actual bug here (which i doubt, that would rather be something systemic than the app IMHO)

the notification is bound to certain conditions, but you do not use the app under these conditions but under some that i did not take into account when planning it. i want to make sure it works as desired under the conditions it is supposed to work before adjusting these conditions ...

**Comment by ogra1** [comment]
please check with the latest release, the badge counter is not bound to the app focus anymore so it should persist until all notifications are processed manually in the app
